credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith  
      password: abc
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$CIFhEoENbUekxIa6ZvY.ceRhdQdnzPIsokdNeyC64KKr6rurEXxG6 

cookie:
  expiry_days: 30
  key: ase0123ksf21ubnuy3o2hsiu721y3kjd722jfq8ueh12eo1287e2ho21i3u22jh1b40183hio1uy # Must be string
  name: calorie_counter

preauthorized:
  emails:
  - melsby@gmail.com